# Generated by Django 5.1.3 on 2024-11-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carousel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download', to='carousel.carousel')),
            ],
        ),
    ]
