# Generated by Django 5.1.3 on 2024-11-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images_generated', '0001_initial'),
        ('texte', '0001_initial'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='themes.theme')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='carousel.carousel')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images_generated.generatedimage')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texte.generatedtext')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
